app:
  port: "8010"

database:
  host: localhost
  port: 5432
  name: payment
  password: admin
  user: postgres

redis:
  host: 127.0.0.1
  port: 6379
  password: root

kafka:
  broker: localhost:9093
  topics:
    - order.created: order.created
    - payment.success: payment.success
pga:
  api_key: "xnd_development_gJ7XYKLk8yCdFgIXmf6XDrNpqGGbJZrOGx0rY4wc25aCr3NhiULHRZZPKhtQc"
  webhook_token: "BGbj1zUFbv0QSEn2lTBKnpFi5ZkA6dDhvnLGf1TX9CLSGOws"

toggle:
  disable_create_payment_invoice_directly: true