app:
  port: "8010"

database:
  host: localhost
  port: 5432
  name: payment
  password: admin
  user: postgres

redis:
  host: 127.0.0.1
  port: 6379
  password: root

kafka:
  broker: localhost:9093
  topics:
    - order.created: order.created
    - payment.success: payment.success
